In [1]:
from tensorflow.keras.preprocessing.text import one_hot

In [2]:
#sentences
sent = [
    'the glass of milk',
    'the glass of juice',
    'the cup of tea',
    'I am a good student',
    'your video is great',
    'learning is a continuous process',
    'I love deep learning'
] 

In [3]:
sent

['the glass of milk',
 'the glass of juice',
 'the cup of tea',
 'I am a good student',
 'your video is great',
 'learning is a continuous process',
 'I love deep learning']

In [4]:
## Define vocabulary size
vocab_size = 10000

In [5]:
##one-hot  representation
one_hot_repr = [one_hot(words, vocab_size) for words in sent]

In [6]:
one_hot_repr

[[4648, 6921, 7898, 1171],
 [4648, 6921, 7898, 7796],
 [4648, 1088, 7898, 2166],
 [5640, 5974, 2950, 1713, 624],
 [7105, 8876, 96, 3488],
 [2205, 96, 2950, 7719, 1411],
 [5640, 4378, 2811, 2205]]

In [7]:
##word embedding representation
from tensorflow.keras.layers import Embedding
from tensorflow.keras.utils import pad_sequences
from tensorflow.keras.models import Sequential

In [8]:
import numpy as np

In [9]:
sent_length = 9
embedded_docs = pad_sequences(one_hot_repr, padding='pre', maxlen=sent_length)
print(embedded_docs)

[[   0    0    0    0    0 4648 6921 7898 1171]
 [   0    0    0    0    0 4648 6921 7898 7796]
 [   0    0    0    0    0 4648 1088 7898 2166]
 [   0    0    0    0 5640 5974 2950 1713  624]
 [   0    0    0    0    0 7105 8876   96 3488]
 [   0    0    0    0 2205   96 2950 7719 1411]
 [   0    0    0    0    0 5640 4378 2811 2205]]


In [10]:
#feature represtation
dim=10

In [11]:
model = Sequential()
model.add(Embedding(vocab_size, dim, input_length=sent_length))
model.compile(optimizer='adam', loss='mse')

e:\simple_rnn\venv\Lib\site-packages\keras\src\layers\core\embedding.py:97: UserWarning: Argument `input_length` is deprecated. Just remove it.
  warnings.warn(


In [14]:
model.build(input_shape=(None, sent_length))
model.summary()

Model: "sequential"

┏━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━┓
┃ Layer (type)                    ┃ Output Shape           ┃       Param # ┃
┡━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━┩
│ embedding (Embedding)           │ (None, 9, 10)          │       100,000 │
└─────────────────────────────────┴────────────────────────┴───────────────┘

 Total params: 100,000 (390.62 KB)

 Trainable params: 100,000 (390.62 KB)

 Non-trainable params: 0 (0.00 B)

In [15]:
model.predict(embedded_docs)

1/1 ━━━━━━━━━━━━━━━━━━━━ 2s 2s/step


array([[[-0.00545614, -0.02280885, -0.00591488, -0.01422372,
         -0.03414863, -0.02777766,  0.01434226,  0.04577157,
          0.0200665 ,  0.01557679],
        [-0.00545614, -0.02280885, -0.00591488, -0.01422372,
         -0.03414863, -0.02777766,  0.01434226,  0.04577157,
          0.0200665 ,  0.01557679],
        [-0.00545614, -0.02280885, -0.00591488, -0.01422372,
         -0.03414863, -0.02777766,  0.01434226,  0.04577157,
          0.0200665 ,  0.01557679],
        [-0.00545614, -0.02280885, -0.00591488, -0.01422372,
         -0.03414863, -0.02777766,  0.01434226,  0.04577157,
          0.0200665 ,  0.01557679],
        [-0.00545614, -0.02280885, -0.00591488, -0.01422372,
         -0.03414863, -0.02777766,  0.01434226,  0.04577157,
          0.0200665 ,  0.01557679],
        [ 0.00040331, -0.01027023,  0.02988878,  0.04427706,
         -0.04282284, -0.00615953,  0.04518409,  0.04567596,
          0.04524298, -0.03566356],
        [ 0.01661085,  0.0381675 , -0.00730287,  0.0

In [16]:
embedded_docs[0]

array([   0,    0,    0,    0,    0, 4648, 6921, 7898, 1171], dtype=int32)